security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory:
            memory:
                users:
                    apiuser:
                        password: '$2y$13$eyW6f0t5ZkqzRMOZ11mv5uLGQPX//FvyjhDcECG5MDB.Jv9pqXARm'
                        roles: 'ROLE_API'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_protected:
            pattern: ^/api-protege.php
            stateless: true
            http_basic:
                provider: users_in_memory

        main:
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/api-protege.php, roles: ROLE_API }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
